services:
  - type: web
    name: spacy-lemmatizer-api
    env: python
    plan: free # ou "starter" si vous avez besoin de plus de puissance
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
